Remove the --rm flag
Seems to be causing failures on circleci:

============================= test session starts
==============================
platform linux -- Python 3.5.3, pytest-3.0.6, py-1.4.31, pluggy-0.4.0 --
/opt/conda/bin/python
cachedir: .cache
rootdir: /usr/src/app, inifile: pytest.ini
collecting 0 itemscollecting 0 itemscollected 0 items

========================= no tests ran in 0.46 seconds
=========================
ERROR: Unable to remove filesystem for
b34d5124251ac514a78400b4a1efff1d97142c72e928e06b5cdb977277dc1640: remove
/var/lib/docker/containers/b34d5124251ac514a78400b4a1efff1d97142c72e928e06b5cdb977277dc1640/shm:
device or resource busy